import { Chapters } from '../types/chapters'

const chapters: Chapters = {
    Belgium: 'https://www.internetsociety.be/',
    Argentina: 'http://www.isoc.org.ar/',
    Armenia: 'https://www.isocchapter.am/',
    Australia: 'https://www.internet.org.au/',
    Bahrain: 'http://www.isoc.bh/',
    Bangladesh: 'https://internetsociety.org.bd/',
    Benin: 'https://www.isoc.bj/',
    Bolivia: 'http://www.isoc.bo/',
    'Bosnia and Herz.': 'https://www.internetsociety.ba/',
    Botswana: 'https://www.isoc.org.bw/',
    Brazil: 'https://www.isoc.org.br/',
    Bulgaria: 'https://www.isoc.bg/',
    'Burkina Faso': 'http://isoc-burkina.org/',
    Burundi: 'http://isoc.bi/',
    Cameroon: 'https://www.isoc-cameroon.org/',
    Canada: [
        {
            url: 'http://www.internetsociety.ca/',
            location: {
                longitude: 0,
                latitude: 0,
            },
        },
        {
            url: 'https://isoc.quebec/',
            location: {
                longitude: 0,
                latitude: 0,
            },
        },
        {
            url: 'https://www.internetsocietymanitoba.ca/',
            location: {
                longitude: 0,
                latitude: 0,
            },
        },
    ],
    Chad: 'https://isoc.td/',
    Chile: 'https://www.facebook.com/InternetSocietyCapituloChile/',
    Colombia: 'https://isoc.co/',
    Comoros: 'https://isoc.km/',
    Congo: 'http://www.isoc.cg/',
    'Costa Rica': 'https://www.facebook.com/internetsocietycr/',
    "Côte d'Ivoire": 'https://internetsociety.ci/',
    'Dem. Rep. Congo': 'https://www.isocrdc.org/',
    Dominica: 'http://isoc.dm/',
    'Dominican Rep.': 'https://isoc.do/',
    Ecuador: 'http://www.isoc.org.ec/',
    Egypt: 'https://www.internetmasr.org/',
    'El Salvador': 'http://www.isoc.sv/',
    Estonia: 'http://isoc.ee/',
    Finland: 'http://www.isoc.fi/',
    France: 'https://www.isoc.fr/',
    Gambia: 'http://isoc.gm/',
    Georgia: 'https://isoc.ge/',
    Germany: 'https://www.isoc.de/',
    Ghana: 'http://www.isoc.gh/',
    Guatemala: 'https://www.isoc.org.gt/',
    Guinea: 'http://www.isoc.org.gn/',
    Guyana: 'https://www.facebook.com/Internetsocietyguyana/',
    Haiti: 'https://www.isoc.ht/',
    Honduras: 'http://isoc.org.hn/',
    'Hong Kong': 'http://www.isoc.hk/',
    Israel: 'http://www.isoc.org.il/',
    India: [
        {
            url: 'http://isocindiachennai.org/',
            location: {
                longitude: 0,
                latitude: 0,
            },
        },
        {
            url: 'https://www.isocindiahyderabad.org/',
            location: {
                longitude: 0,
                latitude: 0,
            },
        },
        {
            url: 'https://isocindiamumbai.org/',
            location: {
                longitude: 0,
                latitude: 0,
            },
        },
        {
            url: 'https://isockolkata.in/',
            location: {
                longitude: 0,
                latitude: 0,
            },
        },
        {
            url: 'http://isoctrv.in/',
            location: {
                longitude: 0,
                latitude: 0,
            },
        },
    ],
    Italy: 'http://www.isoc.it/',
    Jamaica: 'https://isocjm.org/',
    Japan: 'https://www.isoc.jp/',
    Kazakhstan: 'http://internetsociety.kz/',
    Kenya: 'http://www.isoc.or.ke/',
    Kyrgyzstan: 'https://isoc.kg/',
    Lebanon: 'http://www.isoc.org.lb/',
    Lesotho: 'https://isoc.org.ls/',
    Liberia: 'https://internetsociety.org.lr/',
    Madagascar: 'http://isoc.mg/',
    Malaysia: 'https://isoc.my/',
    Mali: 'http://www.isoc.ml/',
    Mexico: 'http://www.isoc.mx/',
    Montenegro: 'http://isoc.me/',
    Morocco: 'https://www.misoc.ma/',
    Namibia: 'https://isocnamibia.org/',
    Netherlands: 'https://isoc.nl/',
    Nicaragua: 'http://isoc.org.ni/',
    Nigeria: 'http://www.isoc.ng/',
    Norway: 'https://isoc.no/',
    Panama: 'http://www.isoc.org.pa/',
    Paraguay: 'http://www.isoc.org.py/',
    Peru: 'http://isoc.pe/',
    Philippines: 'https://www.facebook.com/isoc.ph/',
    Poland: 'https://internetsocietypoland.org/',
    'Puerto Rico': 'http://www.isocpr.org/',
    Portugal: 'https://isoc.pt/',
    Russia: 'https://www.isocru.org/',
    Rwanda: 'https://www.internetsociety.rw/',
    'St. Vin. and Gren.': 'https://www.isoc.vc/',
    Senegal: 'https://www.isoc.sn/',
    Serbia: 'https://isoc.rs/',
    'Sierra Leone': 'https://www.isoc-sl.org/',
    Singapore: 'https://isocsg.org/',
    Slovenia: 'http://www.isoc.si/',
    Somalia: 'https://som-isoc.org/',
    'South Africa': 'http://internetsouthafrica.org.za/',
    'Sri Lanka': 'http://www.isoc.lk/',
    Sudan: 'http://isoc.sd/',
    Sweden: 'https://www.isoc.se/',
    Spain: [
        {
            url: 'http://www.isoc-es.org/',
            location: {
                longitude: 0,
                latitude: 0,
            },
        },
        {
            url: 'http://isoc-aragon.org/',
            location: {
                longitude: 0,
                latitude: 0,
            },
        },
        {
            url: 'https://www.isoc.cat/',
            location: {
                longitude: 0,
                latitude: 0,
            },
        },
    ],
    Switzerland: 'https://www.isoc.ch/',
    Taiwan: 'http://www.isoc.org.tw/',
    Tanzania: 'https://www.isoc.ne.tz/',
    Togo: 'http://www.internetsociety.tg/',
    'Trinidad and Tobago': 'https://www.isoc.tt/',
    Tunisia: 'http://www.isoc.tn/',
    Turkey: 'https://isoc.org.tr/',
    'United Kingdom': 'http://www.isoc-e.org/',
    'United States of America': [
        {
            url: 'https://isoc-ny.org/',
            location: {
                longitude: 0,
                latitude: 0,
            },
        },
        {
            url: 'https://www.sfbayisoc.org/',
            location: {
                longitude: 0,
                latitude: 0,
            },
        },
        {
            url: 'https://isoc-phila.org/',
            location: {
                longitude: 0,
                latitude: 0,
            },
        },
        {
            url: 'https://isoc-dc.org/',
            location: {
                longitude: 0,
                latitude: 0,
            },
        },
        {
            url: 'https://www.facebook.com/IL.ISOC/',
            location: {
                longitude: 0,
                latitude: 0,
            },
        },
        {
            url: 'http://www.internetsocietynewmexico.org/',
            location: {
                longitude: 0,
                latitude: 0,
            },
        },
    ],
    Uganda: 'https://isoc.ug/',
    Uruguay: 'http://www.isoc.uy/',
    Venezuela: 'https://isocve.org/',
    Yemen: 'http://www.isoc.ye/',
    Zimbabwe: 'http://isoc.org.zw/',
}

export default chapters
