import { type Component } from "solid-js";
import AD from "./AD";
import AE from "./AE";
import AF from "./AF";
import AG from "./AG";
import AI from "./AI";
import AL from "./AL";
import AM from "./AM";
import AO from "./AO";
import AQ from "./AQ";
import AR from "./AR";
import AS from "./AS";
import AT from "./AT";
import AU from "./AU";
import AW from "./AW";
import AX from "./AX";
import AZ from "./AZ";
import BA from "./BA";
import BB from "./BB";
import BD from "./BD";
import BE from "./BE";
import BF from "./BF";
import BG from "./BG";
import BH from "./BH";
import BI from "./BI";
import BJ from "./BJ";
import BL from "./BL";
import BM from "./BM";
import BN from "./BN";
import BO from "./BO";
import BQ from "./BQ";
import BR from "./BR";
import BS from "./BS";
import BT from "./BT";
import BV from "./BV";
import BW from "./BW";
import BY from "./BY";
import BZ from "./BZ";
import CA from "./CA";
import CC from "./CC";
import CD from "./CD";
import CF from "./CF";
import CG from "./CG";
import CH from "./CH";
import CI from "./CI";
import CK from "./CK";
import CL from "./CL";
import CM from "./CM";
import CN from "./CN";
import CO from "./CO";
import CR from "./CR";
import CU from "./CU";
import CV from "./CV";
import CW from "./CW";
import CX from "./CX";
import CY from "./CY";
import CZ from "./CZ";
import DE from "./DE";
import DJ from "./DJ";
import DK from "./DK";
import DM from "./DM";
import DO from "./DO";
import DZ from "./DZ";
import EC from "./EC";
import EE from "./EE";
import EG from "./EG";
import EH from "./EH";
import ER from "./ER";
import ES from "./ES";
import ET from "./ET";
import FI from "./FI";
import FJ from "./FJ";
import FK from "./FK";
import FM from "./FM";
import FO from "./FO";
import FR from "./FR";
import GA from "./GA";
import GB from "./GB";
import GD from "./GD";
import GE from "./GE";
import GF from "./GF";
import GG from "./GG";
import GH from "./GH";
import GI from "./GI";
import GL from "./GL";
import GM from "./GM";
import GN from "./GN";
import GP from "./GP";
import GQ from "./GQ";
import GR from "./GR";
import GS from "./GS";
import GT from "./GT";
import GU from "./GU";
import GW from "./GW";
import GY from "./GY";
import HK from "./HK";
import HM from "./HM";
import HN from "./HN";
import HR from "./HR";
import HT from "./HT";
import HU from "./HU";
import ID from "./ID";
import IE from "./IE";
import IL from "./IL";
import IM from "./IM";
import IN from "./IN";
import IO from "./IO";
import IQ from "./IQ";
import IR from "./IR";
import IS from "./IS";
import IT from "./IT";
import JE from "./JE";
import JM from "./JM";
import JO from "./JO";
import JP from "./JP";
import KE from "./KE";
import KG from "./KG";
import KH from "./KH";
import KI from "./KI";
import KM from "./KM";
import KN from "./KN";
import KP from "./KP";
import KR from "./KR";
import KW from "./KW";
import KY from "./KY";
import KZ from "./KZ";
import LA from "./LA";
import LB from "./LB";
import LC from "./LC";
import LI from "./LI";
import LK from "./LK";
import LR from "./LR";
import LS from "./LS";
import LT from "./LT";
import LU from "./LU";
import LV from "./LV";
import LY from "./LY";
import MA from "./MA";
import MC from "./MC";
import MD from "./MD";
import ME from "./ME";
import MF from "./MF";
import MG from "./MG";
import MH from "./MH";
import MK from "./MK";
import ML from "./ML";
import MM from "./MM";
import MN from "./MN";
import MO from "./MO";
import MP from "./MP";
import MQ from "./MQ";
import MR from "./MR";
import MS from "./MS";
import MT from "./MT";
import MU from "./MU";
import MV from "./MV";
import MW from "./MW";
import MX from "./MX";
import MY from "./MY";
import MZ from "./MZ";
import NA from "./NA";
import NC from "./NC";
import NE from "./NE";
import NF from "./NF";
import NG from "./NG";
import NI from "./NI";
import NL from "./NL";
import NO from "./NO";
import NP from "./NP";
import NR from "./NR";
import NU from "./NU";
import NZ from "./NZ";
import OM from "./OM";
import Other from "./other";
import PA from "./PA";
import PE from "./PE";
import PF from "./PF";
import PG from "./PG";
import PH from "./PH";
import PK from "./PK";
import PL from "./PL";
import PM from "./PM";
import PN from "./PN";
import PR from "./PR";
import PS from "./PS";
import PT from "./PT";
import PW from "./PW";
import PY from "./PY";
import QA from "./QA";
import RE from "./RE";
import RO from "./RO";
import RS from "./RS";
import RU from "./RU";
import RW from "./RW";
import SA from "./SA";
import SB from "./SB";
import SC from "./SC";
import SD from "./SD";
import SE from "./SE";
import SG from "./SG";
import SH from "./SH";
import SI from "./SI";
import SJ from "./SJ";
import SK from "./SK";
import SL from "./SL";
import SM from "./SM";
import SN from "./SN";
import SO from "./SO";
import SR from "./SR";
import SS from "./SS";
import ST from "./ST";
import SV from "./SV";
import SX from "./SX";
import SY from "./SY";
import SZ from "./SZ";
import TC from "./TC";
import TD from "./TD";
import TF from "./TF";
import TG from "./TG";
import TH from "./TH";
import TJ from "./TJ";
import TK from "./TK";
import TL from "./TL";
import TM from "./TM";
import TN from "./TN";
import TO from "./TO";
import TR from "./TR";
import TT from "./TT";
import TV from "./TV";
import TW from "./TW";
import TZ from "./TZ";
import UA from "./UA";
import UG from "./UG";
import UM from "./UM";
import US from "./US";
import UY from "./UY";
import UZ from "./UZ";
import VA from "./VA";
import VC from "./VC";
import VE from "./VE";
import VG from "./VG";
import VI from "./VI";
import VN from "./VN";
import VU from "./VU";
import WF from "./WF";
import WS from "./WS";
import YE from "./YE";
import YT from "./YT";
import ZA from "./ZA";
import ZM from "./ZM";
import ZW from "./ZW";

interface Props {
  code: string;
}
export const Flag: Component<Props> = (props) => {
  const getFlag = (code: string) => {
    code = code.toUpperCase();
    if (code === "AD") return <AD />;
    else if (code === "AE") return <AE />;
    else if (code === "AF") return <AF />;
    else if (code === "AG") return <AG />;
    else if (code === "AI") return <AI />;
    else if (code === "AL") return <AL />;
    else if (code === "AM") return <AM />;
    else if (code === "AO") return <AO />;
    else if (code === "AQ") return <AQ />;
    else if (code === "AR") return <AR />;
    else if (code === "AS") return <AS />;
    else if (code === "AT") return <AT />;
    else if (code === "AU") return <AU />;
    else if (code === "AW") return <AW />;
    else if (code === "AX") return <AX />;
    else if (code === "AZ") return <AZ />;
    else if (code === "BA") return <BA />;
    else if (code === "BB") return <BB />;
    else if (code === "BD") return <BD />;
    else if (code === "BE") return <BE />;
    else if (code === "BF") return <BF />;
    else if (code === "BG") return <BG />;
    else if (code === "BH") return <BH />;
    else if (code === "BI") return <BI />;
    else if (code === "BJ") return <BJ />;
    else if (code === "BL") return <BL />;
    else if (code === "BM") return <BM />;
    else if (code === "BN") return <BN />;
    else if (code === "BO") return <BO />;
    else if (code === "BQ") return <BQ />;
    else if (code === "BR") return <BR />;
    else if (code === "BS") return <BS />;
    else if (code === "BT") return <BT />;
    else if (code === "BV") return <BV />;
    else if (code === "BW") return <BW />;
    else if (code === "BY") return <BY />;
    else if (code === "BZ") return <BZ />;
    else if (code === "CA") return <CA />;
    else if (code === "CC") return <CC />;
    else if (code === "CD") return <CD />;
    else if (code === "CF") return <CF />;
    else if (code === "CG") return <CG />;
    else if (code === "CH") return <CH />;
    else if (code === "CI") return <CI />;
    else if (code === "CK") return <CK />;
    else if (code === "CL") return <CL />;
    else if (code === "CM") return <CM />;
    else if (code === "CN") return <CN />;
    else if (code === "CO") return <CO />;
    else if (code === "CR") return <CR />;
    else if (code === "CU") return <CU />;
    else if (code === "CV") return <CV />;
    else if (code === "CW") return <CW />;
    else if (code === "CX") return <CX />;
    else if (code === "CY") return <CY />;
    else if (code === "CZ") return <CZ />;
    else if (code === "DE") return <DE />;
    else if (code === "DJ") return <DJ />;
    else if (code === "DK") return <DK />;
    else if (code === "DM") return <DM />;
    else if (code === "DO") return <DO />;
    else if (code === "DZ") return <DZ />;
    else if (code === "EC") return <EC />;
    else if (code === "EE") return <EE />;
    else if (code === "EG") return <EG />;
    else if (code === "EH") return <EH />;
    else if (code === "ER") return <ER />;
    else if (code === "ES") return <ES />;
    else if (code === "ET") return <ET />;
    else if (code === "FI") return <FI />;
    else if (code === "FJ") return <FJ />;
    else if (code === "FK") return <FK />;
    else if (code === "FM") return <FM />;
    else if (code === "FO") return <FO />;
    else if (code === "FR") return <FR />;
    else if (code === "GA") return <GA />;
    else if (code === "GB") return <GB />;
    else if (code === "GD") return <GD />;
    else if (code === "GE") return <GE />;
    else if (code === "GF") return <GF />;
    else if (code === "GG") return <GG />;
    else if (code === "GH") return <GH />;
    else if (code === "GI") return <GI />;
    else if (code === "GL") return <GL />;
    else if (code === "GM") return <GM />;
    else if (code === "GN") return <GN />;
    else if (code === "GP") return <GP />;
    else if (code === "GQ") return <GQ />;
    else if (code === "GR") return <GR />;
    else if (code === "GS") return <GS />;
    else if (code === "GT") return <GT />;
    else if (code === "GU") return <GU />;
    else if (code === "GW") return <GW />;
    else if (code === "GY") return <GY />;
    else if (code === "HK") return <HK />;
    else if (code === "HM") return <HM />;
    else if (code === "HN") return <HN />;
    else if (code === "HR") return <HR />;
    else if (code === "HT") return <HT />;
    else if (code === "HU") return <HU />;
    else if (code === "ID") return <ID />;
    else if (code === "IE") return <IE />;
    else if (code === "IL") return <IL />;
    else if (code === "IM") return <IM />;
    else if (code === "IN") return <IN />;
    else if (code === "IO") return <IO />;
    else if (code === "IQ") return <IQ />;
    else if (code === "IR") return <IR />;
    else if (code === "IS") return <IS />;
    else if (code === "IT") return <IT />;
    else if (code === "JE") return <JE />;
    else if (code === "JM") return <JM />;
    else if (code === "JO") return <JO />;
    else if (code === "JP") return <JP />;
    else if (code === "KE") return <KE />;
    else if (code === "KG") return <KG />;
    else if (code === "KH") return <KH />;
    else if (code === "KI") return <KI />;
    else if (code === "KM") return <KM />;
    else if (code === "KN") return <KN />;
    else if (code === "KP") return <KP />;
    else if (code === "KR") return <KR />;
    else if (code === "KW") return <KW />;
    else if (code === "KY") return <KY />;
    else if (code === "KZ") return <KZ />;
    else if (code === "LA") return <LA />;
    else if (code === "LB") return <LB />;
    else if (code === "LC") return <LC />;
    else if (code === "LI") return <LI />;
    else if (code === "LK") return <LK />;
    else if (code === "LR") return <LR />;
    else if (code === "LS") return <LS />;
    else if (code === "LT") return <LT />;
    else if (code === "LU") return <LU />;
    else if (code === "LV") return <LV />;
    else if (code === "LY") return <LY />;
    else if (code === "MA") return <MA />;
    else if (code === "MC") return <MC />;
    else if (code === "MD") return <MD />;
    else if (code === "ME") return <ME />;
    else if (code === "MF") return <MF />;
    else if (code === "MG") return <MG />;
    else if (code === "MH") return <MH />;
    else if (code === "MK") return <MK />;
    else if (code === "ML") return <ML />;
    else if (code === "MM") return <MM />;
    else if (code === "MN") return <MN />;
    else if (code === "MO") return <MO />;
    else if (code === "MP") return <MP />;
    else if (code === "MQ") return <MQ />;
    else if (code === "MR") return <MR />;
    else if (code === "MS") return <MS />;
    else if (code === "MT") return <MT />;
    else if (code === "MU") return <MU />;
    else if (code === "MV") return <MV />;
    else if (code === "MW") return <MW />;
    else if (code === "MX") return <MX />;
    else if (code === "MY") return <MY />;
    else if (code === "MZ") return <MZ />;
    else if (code === "NA") return <NA />;
    else if (code === "NC") return <NC />;
    else if (code === "NE") return <NE />;
    else if (code === "NF") return <NF />;
    else if (code === "NG") return <NG />;
    else if (code === "NI") return <NI />;
    else if (code === "NL") return <NL />;
    else if (code === "NO") return <NO />;
    else if (code === "NP") return <NP />;
    else if (code === "NR") return <NR />;
    else if (code === "NU") return <NU />;
    else if (code === "NZ") return <NZ />;
    else if (code === "OM") return <OM />;
    else if (code === "PA") return <PA />;
    else if (code === "PE") return <PE />;
    else if (code === "PF") return <PF />;
    else if (code === "PG") return <PG />;
    else if (code === "PH") return <PH />;
    else if (code === "PK") return <PK />;
    else if (code === "PL") return <PL />;
    else if (code === "PM") return <PM />;
    else if (code === "PN") return <PN />;
    else if (code === "PR") return <PR />;
    else if (code === "PS") return <PS />;
    else if (code === "PT") return <PT />;
    else if (code === "PW") return <PW />;
    else if (code === "PY") return <PY />;
    else if (code === "QA") return <QA />;
    else if (code === "RE") return <RE />;
    else if (code === "RO") return <RO />;
    else if (code === "RS") return <RS />;
    else if (code === "RU") return <RU />;
    else if (code === "RW") return <RW />;
    else if (code === "SA") return <SA />;
    else if (code === "SB") return <SB />;
    else if (code === "SC") return <SC />;
    else if (code === "SD") return <SD />;
    else if (code === "SE") return <SE />;
    else if (code === "SG") return <SG />;
    else if (code === "SH") return <SH />;
    else if (code === "SI") return <SI />;
    else if (code === "SJ") return <SJ />;
    else if (code === "SK") return <SK />;
    else if (code === "SL") return <SL />;
    else if (code === "SM") return <SM />;
    else if (code === "SN") return <SN />;
    else if (code === "SO") return <SO />;
    else if (code === "SR") return <SR />;
    else if (code === "SS") return <SS />;
    else if (code === "ST") return <ST />;
    else if (code === "SV") return <SV />;
    else if (code === "SX") return <SX />;
    else if (code === "SY") return <SY />;
    else if (code === "SZ") return <SZ />;
    else if (code === "TC") return <TC />;
    else if (code === "TD") return <TD />;
    else if (code === "TF") return <TF />;
    else if (code === "TG") return <TG />;
    else if (code === "TH") return <TH />;
    else if (code === "TJ") return <TJ />;
    else if (code === "TK") return <TK />;
    else if (code === "TL") return <TL />;
    else if (code === "TM") return <TM />;
    else if (code === "TN") return <TN />;
    else if (code === "TO") return <TO />;
    else if (code === "TR") return <TR />;
    else if (code === "TT") return <TT />;
    else if (code === "TV") return <TV />;
    else if (code === "TW") return <TW />;
    else if (code === "TZ") return <TZ />;
    else if (code === "UA") return <UA />;
    else if (code === "UG") return <UG />;
    else if (code === "UM") return <UM />;
    else if (code === "US") return <US />;
    else if (code === "UY") return <UY />;
    else if (code === "UZ") return <UZ />;
    else if (code === "VA") return <VA />;
    else if (code === "VC") return <VC />;
    else if (code === "VE") return <VE />;
    else if (code === "VG") return <VG />;
    else if (code === "VI") return <VI />;
    else if (code === "VN") return <VN />;
    else if (code === "VU") return <VU />;
    else if (code === "WF") return <WF />;
    else if (code === "WS") return <WS />;
    else if (code === "YE") return <YE />;
    else if (code === "YT") return <YT />;
    else if (code === "ZA") return <ZA />;
    else if (code === "ZM") return <ZM />;
    else if (code === "ZW") return <ZW />;
    else return <Other />;
  };
  return <>{getFlag(props.code)}</>;
};
