name: CI

on:
  workflow_dispatch:
  push:
    branches: ["v2"]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: write

jobs:
  format:
    name: Format
    timeout-minutes: 1
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Format
        run: npm run format

      - name: Git push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if git status | grep -q modified; then
            git commit -m "style: automatic formatting"
            git push
          fi

  lint:
    name: Lint
    timeout-minutes: 1
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  check_types:
    name: Check types
    timeout-minutes: 1
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run check-types

  test:
    name: Test
    needs: [lint, check_types]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test
